### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by marceloavf** [geeklearningio/gl-vsts-tasks-build-scripts#28]
Hi,

I can't build some projects on ubuntu and I'm getting this error:

```
yarn install v1.22.5
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > ts-jest@23.0.1" has unmet peer dependency "babel-core@^6.26.3 || ^7.0.0-0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
$ vsts-build-tools-install
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

As I'm searching for, it seems to be related to Lines Ending, when I went to the .bin folder on node_modules and change from CRLF to LF it works normally.

**Comment by sandorfr** [comment]
I've published your PR : 0.7.0-alpha.7

Let me know how it goes

**Comment by marceloavf** [comment]
@sandorfr Still the same error, maybe force lf on .gitattributes?
